name: agrota_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^17.0.0
  icons_launcher: ^2.1.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

